<?php

namespace AppBundle\Repository;

/**
 * OrdrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdrRepository extends \Doctrine\ORM\EntityRepository
{
}
